SELECT JOB_ID,
  SUM (SALARY) AS SOMA_SALARIO,
  MAX (SALARY) AS MAXIMO_SALARIO,
  MIN (SALARY) AS MINIMO_SALARIO,
  AVG (SALARY) AS MEDIA_SALARIO
FROM EMPLOYEES_RH
WHERE DEPARTMENT_ID = 90
GROUP BY JOB_ID;
